[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastapi-cookie-auth"
version = "1.0.0"
description = "A lightweight FastAPI library for secure cookie-based authentication, supporting both OAuth2 and Sessions with built-in CSRF protection."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Denis Lyovin", email = "DOS1918@proton.me" },
]
dependencies = [
    "fastapi>=0.95.0",
]

[tool.poe.tasks]
oauth2 = "uv run fastapi dev dev/oauth2.py"
session = "uv run fastapi dev dev/session.py"
test = "uv run pytest"
build = "uv build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "httpx2>=2.12.0",
    "fastapi[standard]>=0.141.1",
    "poethepoet>=0.48.0",
]

[project.urls]
Homepage = "https://github.com/D1918/fastapi-cookie-auth.git"

[tool.hatch.build.targets.sdist]
exclude = [
    "1.md",
    "uv.lock",
    ".gitignore",
    "tests/",
    "dev/",
    "examples/"
]

[tool.hatch.build.targets.wheel]
packages = ["fastapi_cookie_auth"]
